/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MerchantsRouteImport } from './routes/merchants'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CustomsRouteImport } from './routes/customs'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkflowsIndexRouteImport } from './routes/workflows.index'
import { Route as RequestsIndexRouteImport } from './routes/requests.index'
import { Route as RequestsNewRouteImport } from './routes/requests.new'
import { Route as RequestsIdRouteImport } from './routes/requests.$id'
import { Route as AdminWorkflowsRouteImport } from './routes/admin.workflows'
import { Route as AdminWorkflowDocsRouteImport } from './routes/admin.workflow-docs'
import { Route as AdminTeamsRouteImport } from './routes/admin.teams'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminScreenPermissionsRouteImport } from './routes/admin.screen-permissions'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminReferenceDataRouteImport } from './routes/admin.reference-data'
import { Route as AdminOrgsRouteImport } from './routes/admin.orgs'
import { Route as AdminEntitiesRouteImport } from './routes/admin.entities'
import { Route as WorkflowsInstancesIdRouteImport } from './routes/workflows.instances.$id'
import { Route as RequestsIdSwiftRouteImport } from './routes/requests.$id.swift'
import { Route as CustomsIdPrintRouteImport } from './routes/customs.$id.print'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantsRoute = MerchantsRouteImport.update({
  id: '/merchants',
  path: '/merchants',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomsRoute = CustomsRouteImport.update({
  id: '/customs',
  path: '/customs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIndexRoute = WorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIndexRoute = RequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsNewRoute = RequestsNewRouteImport.update({
  id: '/requests/new',
  path: '/requests/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIdRoute = RequestsIdRouteImport.update({
  id: '/requests/$id',
  path: '/requests/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWorkflowsRoute = AdminWorkflowsRouteImport.update({
  id: '/admin/workflows',
  path: '/admin/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWorkflowDocsRoute = AdminWorkflowDocsRouteImport.update({
  id: '/admin/workflow-docs',
  path: '/admin/workflow-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamsRoute = AdminTeamsRouteImport.update({
  id: '/admin/teams',
  path: '/admin/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/admin/staff',
  path: '/admin/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminScreenPermissionsRoute = AdminScreenPermissionsRouteImport.update({
  id: '/admin/screen-permissions',
  path: '/admin/screen-permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReferenceDataRoute = AdminReferenceDataRouteImport.update({
  id: '/admin/reference-data',
  path: '/admin/reference-data',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrgsRoute = AdminOrgsRouteImport.update({
  id: '/admin/orgs',
  path: '/admin/orgs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEntitiesRoute = AdminEntitiesRouteImport.update({
  id: '/admin/entities',
  path: '/admin/entities',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsInstancesIdRoute = WorkflowsInstancesIdRouteImport.update({
  id: '/workflows/instances/$id',
  path: '/workflows/instances/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIdSwiftRoute = RequestsIdSwiftRouteImport.update({
  id: '/swift',
  path: '/swift',
  getParentRoute: () => RequestsIdRoute,
} as any)
const CustomsIdPrintRoute = CustomsIdPrintRouteImport.update({
  id: '/$id/print',
  path: '/$id/print',
  getParentRoute: () => CustomsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/customs': typeof CustomsRouteWithChildren
  '/login': typeof LoginRoute
  '/merchants': typeof MerchantsRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/admin/entities': typeof AdminEntitiesRoute
  '/admin/orgs': typeof AdminOrgsRoute
  '/admin/reference-data': typeof AdminReferenceDataRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/screen-permissions': typeof AdminScreenPermissionsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/workflow-docs': typeof AdminWorkflowDocsRoute
  '/admin/workflows': typeof AdminWorkflowsRoute
  '/requests/$id': typeof RequestsIdRouteWithChildren
  '/requests/new': typeof RequestsNewRoute
  '/requests/': typeof RequestsIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/customs/$id/print': typeof CustomsIdPrintRoute
  '/requests/$id/swift': typeof RequestsIdSwiftRoute
  '/workflows/instances/$id': typeof WorkflowsInstancesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/customs': typeof CustomsRouteWithChildren
  '/login': typeof LoginRoute
  '/merchants': typeof MerchantsRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/admin/entities': typeof AdminEntitiesRoute
  '/admin/orgs': typeof AdminOrgsRoute
  '/admin/reference-data': typeof AdminReferenceDataRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/screen-permissions': typeof AdminScreenPermissionsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/workflow-docs': typeof AdminWorkflowDocsRoute
  '/admin/workflows': typeof AdminWorkflowsRoute
  '/requests/$id': typeof RequestsIdRouteWithChildren
  '/requests/new': typeof RequestsNewRoute
  '/requests': typeof RequestsIndexRoute
  '/workflows': typeof WorkflowsIndexRoute
  '/customs/$id/print': typeof CustomsIdPrintRoute
  '/requests/$id/swift': typeof RequestsIdSwiftRoute
  '/workflows/instances/$id': typeof WorkflowsInstancesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/customs': typeof CustomsRouteWithChildren
  '/login': typeof LoginRoute
  '/merchants': typeof MerchantsRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/admin/entities': typeof AdminEntitiesRoute
  '/admin/orgs': typeof AdminOrgsRoute
  '/admin/reference-data': typeof AdminReferenceDataRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/screen-permissions': typeof AdminScreenPermissionsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/workflow-docs': typeof AdminWorkflowDocsRoute
  '/admin/workflows': typeof AdminWorkflowsRoute
  '/requests/$id': typeof RequestsIdRouteWithChildren
  '/requests/new': typeof RequestsNewRoute
  '/requests/': typeof RequestsIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/customs/$id/print': typeof CustomsIdPrintRoute
  '/requests/$id/swift': typeof RequestsIdSwiftRoute
  '/workflows/instances/$id': typeof WorkflowsInstancesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/customs'
    | '/login'
    | '/merchants'
    | '/notifications'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/admin/entities'
    | '/admin/orgs'
    | '/admin/reference-data'
    | '/admin/roles'
    | '/admin/screen-permissions'
    | '/admin/staff'
    | '/admin/teams'
    | '/admin/workflow-docs'
    | '/admin/workflows'
    | '/requests/$id'
    | '/requests/new'
    | '/requests/'
    | '/workflows/'
    | '/customs/$id/print'
    | '/requests/$id/swift'
    | '/workflows/instances/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/customs'
    | '/login'
    | '/merchants'
    | '/notifications'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/admin/entities'
    | '/admin/orgs'
    | '/admin/reference-data'
    | '/admin/roles'
    | '/admin/screen-permissions'
    | '/admin/staff'
    | '/admin/teams'
    | '/admin/workflow-docs'
    | '/admin/workflows'
    | '/requests/$id'
    | '/requests/new'
    | '/requests'
    | '/workflows'
    | '/customs/$id/print'
    | '/requests/$id/swift'
    | '/workflows/instances/$id'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/customs'
    | '/login'
    | '/merchants'
    | '/notifications'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/admin/entities'
    | '/admin/orgs'
    | '/admin/reference-data'
    | '/admin/roles'
    | '/admin/screen-permissions'
    | '/admin/staff'
    | '/admin/teams'
    | '/admin/workflow-docs'
    | '/admin/workflows'
    | '/requests/$id'
    | '/requests/new'
    | '/requests/'
    | '/workflows/'
    | '/customs/$id/print'
    | '/requests/$id/swift'
    | '/workflows/instances/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  CustomsRoute: typeof CustomsRouteWithChildren
  LoginRoute: typeof LoginRoute
  MerchantsRoute: typeof MerchantsRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  AdminEntitiesRoute: typeof AdminEntitiesRoute
  AdminOrgsRoute: typeof AdminOrgsRoute
  AdminReferenceDataRoute: typeof AdminReferenceDataRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminScreenPermissionsRoute: typeof AdminScreenPermissionsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminTeamsRoute: typeof AdminTeamsRoute
  AdminWorkflowDocsRoute: typeof AdminWorkflowDocsRoute
  AdminWorkflowsRoute: typeof AdminWorkflowsRoute
  RequestsIdRoute: typeof RequestsIdRouteWithChildren
  RequestsNewRoute: typeof RequestsNewRoute
  RequestsIndexRoute: typeof RequestsIndexRoute
  WorkflowsIndexRoute: typeof WorkflowsIndexRoute
  WorkflowsInstancesIdRoute: typeof WorkflowsInstancesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchants': {
      id: '/merchants'
      path: '/merchants'
      fullPath: '/merchants'
      preLoaderRoute: typeof MerchantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customs': {
      id: '/customs'
      path: '/customs'
      fullPath: '/customs'
      preLoaderRoute: typeof CustomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/': {
      id: '/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof WorkflowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/': {
      id: '/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof RequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/new': {
      id: '/requests/new'
      path: '/requests/new'
      fullPath: '/requests/new'
      preLoaderRoute: typeof RequestsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/$id': {
      id: '/requests/$id'
      path: '/requests/$id'
      fullPath: '/requests/$id'
      preLoaderRoute: typeof RequestsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/workflows': {
      id: '/admin/workflows'
      path: '/admin/workflows'
      fullPath: '/admin/workflows'
      preLoaderRoute: typeof AdminWorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/workflow-docs': {
      id: '/admin/workflow-docs'
      path: '/admin/workflow-docs'
      fullPath: '/admin/workflow-docs'
      preLoaderRoute: typeof AdminWorkflowDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teams': {
      id: '/admin/teams'
      path: '/admin/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AdminTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/admin/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/screen-permissions': {
      id: '/admin/screen-permissions'
      path: '/admin/screen-permissions'
      fullPath: '/admin/screen-permissions'
      preLoaderRoute: typeof AdminScreenPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reference-data': {
      id: '/admin/reference-data'
      path: '/admin/reference-data'
      fullPath: '/admin/reference-data'
      preLoaderRoute: typeof AdminReferenceDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orgs': {
      id: '/admin/orgs'
      path: '/admin/orgs'
      fullPath: '/admin/orgs'
      preLoaderRoute: typeof AdminOrgsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/entities': {
      id: '/admin/entities'
      path: '/admin/entities'
      fullPath: '/admin/entities'
      preLoaderRoute: typeof AdminEntitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/instances/$id': {
      id: '/workflows/instances/$id'
      path: '/workflows/instances/$id'
      fullPath: '/workflows/instances/$id'
      preLoaderRoute: typeof WorkflowsInstancesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/$id/swift': {
      id: '/requests/$id/swift'
      path: '/swift'
      fullPath: '/requests/$id/swift'
      preLoaderRoute: typeof RequestsIdSwiftRouteImport
      parentRoute: typeof RequestsIdRoute
    }
    '/customs/$id/print': {
      id: '/customs/$id/print'
      path: '/$id/print'
      fullPath: '/customs/$id/print'
      preLoaderRoute: typeof CustomsIdPrintRouteImport
      parentRoute: typeof CustomsRoute
    }
  }
}

interface CustomsRouteChildren {
  CustomsIdPrintRoute: typeof CustomsIdPrintRoute
}

const CustomsRouteChildren: CustomsRouteChildren = {
  CustomsIdPrintRoute: CustomsIdPrintRoute,
}

const CustomsRouteWithChildren =
  CustomsRoute._addFileChildren(CustomsRouteChildren)

interface RequestsIdRouteChildren {
  RequestsIdSwiftRoute: typeof RequestsIdSwiftRoute
}

const RequestsIdRouteChildren: RequestsIdRouteChildren = {
  RequestsIdSwiftRoute: RequestsIdSwiftRoute,
}

const RequestsIdRouteWithChildren = RequestsIdRoute._addFileChildren(
  RequestsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  CustomsRoute: CustomsRouteWithChildren,
  LoginRoute: LoginRoute,
  MerchantsRoute: MerchantsRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  AdminEntitiesRoute: AdminEntitiesRoute,
  AdminOrgsRoute: AdminOrgsRoute,
  AdminReferenceDataRoute: AdminReferenceDataRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminScreenPermissionsRoute: AdminScreenPermissionsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminTeamsRoute: AdminTeamsRoute,
  AdminWorkflowDocsRoute: AdminWorkflowDocsRoute,
  AdminWorkflowsRoute: AdminWorkflowsRoute,
  RequestsIdRoute: RequestsIdRouteWithChildren,
  RequestsNewRoute: RequestsNewRoute,
  RequestsIndexRoute: RequestsIndexRoute,
  WorkflowsIndexRoute: WorkflowsIndexRoute,
  WorkflowsInstancesIdRoute: WorkflowsInstancesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
